### ISSUE TITLE
Checkout step 2 with single payment module breaks the DOM

### ISSUE THREAD

**Issue by chindraba-work** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#152]
When there is only one payment module available the DOM gets broken:

- The action line gets moved to the bottom of the page
- The cover for the radio button overlays the start of the payment option
- What looks like a radio button is not one since the input field is `type="hidden"`

Possibly a second issue, but if the DOM is corrected, the dot that looks like radio button is not clickable, and looks like it needs to be selected. The processing does not break, but the customer can be confused by a radio button they cannot select.

Process to create/demonstrate the error:

1. Clean install of Zen-Cart v1.5.6a 01042019
2. Upload ZCA-Bootstrap-Template-for-1.5.6-v2.0.0a-master
3. Select the ZCA Bootstrap template.
4. Activate only one payment module, how many are installed doesn't matter, only activated does.
5. As a customer attempt to checkout with an order.
6. On step 2 examine the page.
7. Notice the opaque square covering the first letter of two (or the corner of the image) of the payment method.
8. Also notice that the "Continue" button seems to be missing. It's at the very bottom, just above the footer.
9. Activate a second payment module.
10. Refresh the checkout step 2 page.
11. Examine the page again, and see that everything is as it should be.

Sample page images are attached below.

[checkout_step_2_issue-a](https://user-images.githubusercontent.com/35464762/57832293-d39bf280-77a6-11e9-8d29-47dd89e558d4.png)
[checkout_step_2_issue-b](https://user-images.githubusercontent.com/35464762/57832297-d7c81000-77a6-11e9-98f3-becefd55cecb.png)

**Comment by chindraba-work** [comment]
@zcadditions  Ok, I'm new to this online collaboration for code so I'm going to get the workflow wrong. Since the change was made that solved this, I thought that closing it was correct. Once I notice the fix, I expected that you'd close it. Seeing it still open I figured that as the one to open it, it was my responsibility to close it. My apologies for apparently preempting your process.

**Comment by zcadditions** [comment]
I can't control what you do. I can only control what I do. I leave GitHub issues open till I push the updated GitHub files to zen cart.

Just easier for me to keep track of all the upgrades to all the different project's

P.S. thanks for your intensive testing and sharing of your findings.

**Comment by chindraba-work** [comment]
Got it. Makes sense to me. Probably helps with doing the change logs too.

First template I've really liked, and best one I've seen since the v1.3.x days. The color controls are an added bonus.

I believe in FLOSS, however one defines or means it, and giving back. I just have to get a handle on git/GitHub and _online_ collaboration.

**Comment by Zen4All** [comment]
off-topic:
@chindraba-work using github looks daunting at first, but it's not that hard. If you download gitkraken for offline development it gets real easy. Gitkraken also has great online documentation, and videos.
