### ISSUE TITLE
Active page number not styled in product listing pages

### ISSUE THREAD

**Issue by chindraba-work** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#154]
When viewing a list of products, in a category or from new/featured, which has more than one page of items, the pagination controls, top/bottom/both depending on settings, has the pages set as buttons. The active page number is _not_ styled to match the row in any way.

![unformated_page_number](https://user-images.githubusercontent.com/35464762/57841968-1cf63d00-77bb-11e9-96a5-cddaa3749688.png)

The lack of styling only affects the listing when the `$outputAsUnorderedList` is true. That is set by `$paginateAsUL` in the calling files.

I don't know if that means this should be closed or not, since without modification bootstrap template doesn't set `$paginateAsUL` true. It only happens when the bootstrap template is merged with some other templates.

**Comment by zcadditions** [comment]
Haven't been able to duplicate this issue as of yet

**Comment by chindraba-work** [comment]
To duplicate this issue the calling file has to set `$paginateAsUL = true` as is done in your ZCA Responsive Classic template in the `html_header.php` file at line 41. Discovered it when trying to incorporate some of that template into this one.
