### ISSUE TITLE
update template files for 1.5.6c

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#167]

**Comment by chindraba-work** [comment]
One of the commits for this issue [6edd46df8e6e0e1a4611bead5102de0a158cb174] changed the file `html_header.php` at line 27 reverting back to the XHTML 1.0 Transitional Doctype from the HTML (5) of modern usage. I don't know what effect that will have in browsers, but it could be a problem.
