### ISSUE TITLE
Should the order-total sections be right-justified (they're currently all left-justified).

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#202]
That formatting is present in the following template files
- tpl_account_history_info_default.php
- tpl_checkout_confirmation_default.php (via tpl_modules_order_total.php)
- tpl_checkout_payment_default.php (via tpl_modules_order_total.php)
- tpl_modules_order_total.php

Looking for opinions; if I don't hear any "No, don't do that!" answers, the justifications will be updated.

**Comment by drbyte** [comment]
IMO I've never cared whether they're right-justified as much as whether the text associated with the numbers is "nearby" and not "all the way over the other side of the screen".

Is it much trouble to post screenshots of both options?

**Comment by chindraba-work** [comment]
Right/left not too big of a deal. Keeping them aligned on the decimal point seems more important than which end of the line.

**Comment by lat9** [comment]
Right justified:
![image](https://user-images.githubusercontent.com/2685585/97472378-2aa47180-1920-11eb-94a3-59dd68b58932.png)

Left-justified:
![image](https://user-images.githubusercontent.com/2685585/97472613-64757800-1920-11eb-9b69-2b986cbbcf9e.png)

**Comment by barco57** [comment]
I vote right justified

**Comment by drbyte** [comment]
I vote for the column of numbers to certainly be right-justified.

For the labels I have no strong preference. I'm mindful that when there are very long strings such as in this example that the eye doesn't know where to go first, but it's not a big deal IMO. 
I'd probably lean toward making sure that the CSS selector which controls the text column is extracted to its own row so it's simple (even obvious) to change without breaking anything else.

**Comment by lat9** [comment]
> 
> 
> I vote for the column of numbers to certainly be right-justified.
> 
> For the labels I have no strong preference. I'm mindful that when there are very long strings such as in this example that the eye doesn't know where to go first, but it's not a big deal IMO.
> I'd probably lean toward making sure that the CSS selector which controls the text column is extracted to its own row so it's simple (even obvious) to change without breaking anything else.

If I'm 'reading' this correctly, you're requesting that a specific `ot-title` and `ot-value` class be defined (the code currently has the `text-right`/`text-left` class hard-coded in the templates) so that a simple change to a .css file will magically make everything aligned the way the site-owner wants?

**Comment by lat9** [comment]
The template's `stylesheet.css` has been updated to (as-shipped) use right-alignment for both the order-totals' titles and text.  Noting that the `account_history_info` and `checkout_confirmation` pages were using a different class to identify each product's price; that's been standardized as `class="totalCell"`.

Stores can now easily adjust the alignment via this section of that stylesheet:
```
.ot-title {
    text-align: right;
}
.ot-text,
.totalCell {
    text-align: right;
}
```
Noting that this change should make it easier to integrate with One-Page Checkout, since it'll be easier to identify the CSS selector setting (Order Total, jQuery Selector) for the order's total value: `#ottotal .ot-text`.

**Comment by drbyte** [comment]
Great! 👍

**Comment by lat9** [comment]
Yes, simple is better.
