### ISSUE TITLE
Additional features need review and possible update

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#209]
At this point, I've captured the various changes that were required for my site's use of the bootstrap template.  I don't use the following features so have no idea if they're going to throw PHP notices and/or warnings (or worse):
- [x] Product Info :: Use Bootstrap Additional Image Carousel
- [x] ~~Product Info :: Use Photoswipe Lightbox.  See [this](https://github.com/dimsemenov/photoswipe) GitHub repository that hasn't been updated for two years.~~.  Feature removed via #242.
- [x] Reviews
- [x] Specials
- [x] Checkout with payment methods that collect card data on-site.

If anyone's using these features, I'd appreciate some help in ensuring that they work properly.

Updated 20201029, adding Reviews, Specials and the 'special checkout' case.

**Comment by drbyte** [comment]
Note: The card-data-on-site thing requires at least merging the recent changes for `tpl_checkout_confirmation_default.php` into `tpl_ajax_checkout_confirmation_default.php`

**Comment by lat9** [comment]
@drbyte, will you take care of that?  I've got no way to validate.
