### ISSUE TITLE
Reduce language-related overrides

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#215]
Many of the language-file overrides (`/includes/languages/english/bootstrap`) are simply additional language constants.  To keep the number of file changes to a minimum, I'm going to pull those new constants out to a bootstrap-template extra_definitions file.

That'll help (I hope) in some of the now-and-future Zen Cart upgrades.

**Comment by drbyte** [comment]
👍

**Comment by lat9** [comment]
Noting that an additional function is needed for those modalboxes, since the code currently _assumes_ that the associated language files are present in the current template's language-directory.

Adding `zca_get_language_dir` as a helper function to reduce these overrides.

**Comment by lat9** [comment]
Migrating common/bootstrap-specific constants to the language's `/extra_definitions/zca_bootstrap_common.php` file.
