### ISSUE TITLE
template_info.php

### ISSUE THREAD

**Issue by drbyte** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#256]
- [x] version bump
- [x] can the link to the readme file about converting to modal be removed or made unnecessary?
- [x] remove trailing `?>`

**Comment by lat9** [comment]
FWIW, my 'plan' is to _eventually_ provide additional, GitHub-based, documentation for the template.  Its additional configuration settings and use of existing should be documented somewhere!

**Comment by lat9** [comment]
There's the 'real' update to the template_info.php!
