### ISSUE TITLE
styling/layout improvements for v300

### ISSUE THREAD

**Issue by drbyte** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#303]
### Banners
- [x] banners in tpl_main_page et al are not centered. Should we add `text-center` to all of them (eg: forced opinionated style) or add a CSS entry just for banners?
    I'm inclined to just do it inline: `<div class="bannerSix rounded text-center">`

### Category Description (see first image)
- [x] There's no containing element for "just the category description" (perhaps also with its title and image). While this is nice on mobile (where sideboxes are gone), it can irritate the eye on desktop.
- [x] There's no padding between the category-description and the filter dropdowns for mfg/alpha. These probably should be in their own containing div.

### Product Listing issues (see 2nd image) (affects index/cats/prod-new-all-featured-specials)
- [x] pagination - selected.  Noting that this (and the following) were displayed properly prior to the zc157a merge.
- [x] paginator - alignment
- [x] column-headings in row-based product-listing (inclined to remove product-image heading, maybe all headings except when sortable)
- [x] padding, esp for prices, in row-based product-listing (see 3rd image, vertical)
- [x] padding below product-listing, above centerboxes (see 4th image)

### Sideboxes (5th image)
- [x] categories sidebox - padding on category separator for selected category

@barco57 do you have some insights on best approaches for some of these?

----

1
<img width="1008" alt="category-description" src="https://user-images.githubusercontent.com/404472/98452973-467af500-2122-11eb-99ea-2e8a2b3c410d.png">

----

2
<img width="968" alt="product-listing-pagination-etc" src="https://user-images.githubusercontent.com/404472/98452472-ac18b280-211d-11eb-8cd3-5051ea876a13.png">

----

3
<img width="175" alt="padding-for-prices" src="https://user-images.githubusercontent.com/404472/98452497-dcf8e780-211d-11eb-8329-9f7415bdfd99.png">

----

4

<img width="728" alt="padding-above-centerboxes" src="https://user-images.githubusercontent.com/404472/98453204-a1ade700-2124-11eb-97e7-b496eca9f27d.png">

----

5
<img width="394" alt="category-separator" src="https://user-images.githubusercontent.com/404472/98452539-1d586580-211e-11eb-8033-e45a4fcd6553.png">

**Comment by lat9** [comment]
Re: Category Description.  The image is present in '#indexProductList-categoryImage' and the description in '#indexProductList-content'.  Do those need additional styling?

I could add a `<div class="p-2"></div>` if the category description is present.

**Comment by lat9** [comment]
For image 4, there's a setting that I'm not finding that displays the listing even if there's only one product.  Where the heck is that?

**Comment by drbyte** [comment]
> For image 4, there's a setting that I'm not finding that displays the listing even if there's only one product. Where the heck is that?

I believe you mean `Admin->Configuration->Layout Settings->Skip 1-prod Categories`
(I would argue that it makes more sense under Product Listing, but that's outside the scope of this template.)

**Comment by drbyte** [comment]
> Re: Category Description. The image is present in '#indexProductList-categoryImage' and the description in '#indexProductList-content'. Do those need additional styling?

I'm undecided. @barco57  ?

> I could add a `<div class="p-2"></div>` if the category description is present.

It would be nice if it could be done without having two conditional checks, eg one for opening div and one for closing div. But that may not be an option if the title/image need to be inside the div.

I'm slightly more inclined to merely (or at the very least) add an unstyled div around it, so that if someone wanted to add a border or apply a background color, etc, at least they can target that specific segment directly via css without having to find the right template file to edit.

**Comment by lat9** [comment]
That change just pushed corrects the display for image-4 (product listing, no space).  Essentially, modifying the zca_split_pages_result class to return `&nbsp;` when there's only one product.

**Comment by lat9** [comment]
Products listing, removing "Product Image" heading.  For rows, use the associated `text-{whatever}` class (was causing a non-HTML5 `align=` attribute to be added).  Additional elements added to the stylesheet for padding and to add a margin above the bottom navigation.

**Comment by lat9** [comment]
That commit corrects the layout for the split-page-results (also some refactoring for readability).

**Comment by lat9** [comment]
The category-related elements on a product-listing is now wrapped via `#indexProductList-cat-wrap`, enabling that/those elements to be containerized.

**Comment by lat9** [comment]
Added a margin below that newly-added element.

**Comment by lat9** [comment]
For item 1 (banner centering), each of the 'main-section' banners (1, 3, 4 and 6) now have a `zca-banner` class and are, by default (via the stylesheet) centered.  Site-specific styling can target a specific banner group, e.g. `.bannerSix` to override the alignment.

**Comment by lat9** [comment]
... and there's the final one, correcting categories sidebox display when a category with sub-categories is the currently-selected category.
