### ISSUE TITLE
sidebars during checkout?

### ISSUE THREAD

**Issue by drbyte** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#305]
Currently the "right column" is being disabled on checkout pages, but not the left column.
To me this feels a little odd.

In `tpl_main_page.php` it's configured to disable **right column only** on the following pages:

`product_info,document_general_info,document_product_info,product_music_info,product_free_shipping_info,`
`shopping_cart,`
`checkout_shipping,checkout_payment,checkout_confirmation,checkout_success`

https://github.com/zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c/blob/d8e3c0c295112cc54ae89a2d214ad4d1d92a9b19/includes/templates/bootstrap/common/tpl_main_page.php#L54-L56

I'm inclined to suggest that we add `$flag_disable_left = true;` there as well.

**Comment by drbyte** [comment]
I'd argue that the `checkout_shipping_address` and `checkout_payment_address` pages might be good additional entries to include in the list.

**Comment by barco57** [comment]
No distractions once you have the customer in the checkout funnel.
