### ISSUE TITLE
Remove no longer used 'PRODUCT_LISTING_LAYOUT_STYLE'

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#311]
... given that I spent the last 15 minutes trying to figure out why changing that from 'columns' to 'rows' didn't have any effect on the pages' rendering.

**Comment by drbyte** [comment]
Ya, v157a makes the use of that switch redundant. Simpler without it.

"Number of columns per row" calculates it automatically: 1 column = `rows` mode; otherwise `columns` mode.

**Comment by drbyte** [comment]
Ref: https://github.com/zencart/zencart/pull/3968

**Comment by lat9** [comment]
Agreed on the simplicity; it'll be removed (if present) by the bootstrap template's admin initialization script.
