### ISSUE TITLE
Back to top button?

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template-for-1.5.6-v2.0.0c#66]
Thinking about including a back to top button. Any input in this?

**Comment by Zen4All** [comment]
good plan

**Comment by lankeeyankee** [comment]
Yes, good idea

**Comment by drbyte** [comment]
Yes, probably good idea. It's easier for people to turn it off or remove it if they don't want it, than to figure out how/where to add it in a way that's most effective.
(I personally never use those things and find them distractingly annoying, but I realize I'm not the typical "user". :) )
